export const ROOM_TYPE = {
  BEDROOM: 0,
  BATHROOM: 1,
  KITCHEN: 2,
  FOYER: 3,
  BREAKFAST: 4,
  LIVINGROOM: 5,
  DININGROOM: 6,
  FAMILYROOM: 7,
  LAUNDRY: 8,
};

export const PROPERTY_TYPE = {
  DETACHED: 0,
  SEMI_DETACHED: 1,
  CONDO_APT: 2,
  ATT_ROW_TWNHOUSE: 3
}

export const ROOM_FEATURE = {
  HARDWOOD_FLOOR: 1,
  POT_LIGHTS: 2,
  WINDOW: 3,
  NATURAL_FINISH: 4,
  GRANITE_COUNTER: 5,
  CENTRE_ISLAND: 6,
  W_I_CLOSET: 7,
  BATH_3_PC: 8,
  BATH_4_PC: 9,
  BATH_5_PC: 10,
  FRENCH_DOORS: 11,
  W_O_TO_YARD: 12,
  LAMINATE: 13,
  W_O_TO_BALCONY: 14,
  COMBINED_W_KITCHEN: 15,
  OPEN_CONCEPT: 16,
  COMBINED_W_DINING: 17,
  CLOSET_B_I_APPLIANCES: 18,
  SLIDING_DOORS: 19,
  FIREPLACE: 20,
  CERAMIC_BACK_SPLASH: 21,
  OVERLOOK_WATER: 22,
  ABOVE_GRADE_WINDOW: 23,
}

export const AIR_CONDITIONING_TYPE = {
  CENTRAL_AIR: 1,
  WALL_UNIT: 2,
  WINDOW_UNIT: 3,
  NONE: 4,
}

export const PROPERTY_EXTERNAL = {
  BRICK: 1,
  BOARD_OR_BATTEN: 2,
  CONCRETE: 3,
  ALUM_SIDING: 4,
  BRICK_FRONT: 5,
  STUCCO_OR_PLASTER: 6,
  WOOD: 7,
}

export const PROPERTY_BASEMENT = {
  NONE: 1,
  UNFINISHED: 2,
  CRAWL_SPACE: 3,
  FINISHED: 4,
}

export const PROPERTY_STATUS = {
  IDENTIFICATION: 0,
  VALUATION: 1,
  UNFRACTIONALIZED_NFT: 2,
  FRACTIONALIZED_NFT_UNPUBLISHED: 3,
  FRACTIONALIZED_NFT_PUBLISHED: 4,
  DELETED: -1
}
